#!/bin/bash 
# written by sleutene
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cp $DIR/CMakeLists.txt $DIR/../../ardrone_autonomy/
cp $DIR/ardrone_sdk.cpp $DIR/../../ardrone_autonomy/src
cp $DIR/video.cpp $DIR/../../ardrone_autonomy/src
cp $DIR/timestamp_hack.patch $DIR/../../ardrone_autonomy/
